# Generated by Django 4.1.7 on 2023-06-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_category_name_en_us_category_name_ru_post_text_en_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoryType_en_us',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='categoryType_ru',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], default='AR', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dateCreation_en_us',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dateCreation_ru',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory_en_us',
            field=models.ManyToManyField(null=True, through='newsapp.PostCategory', to='newsapp.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory_ru',
            field=models.ManyToManyField(null=True, through='newsapp.PostCategory', to='newsapp.category'),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.post')),
            ],
            options={
                'verbose_name': 'post category [ru]',
                'verbose_name_plural': 'post categorys [ru]',
                'db_table': 'newsapp_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.category')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.post')),
            ],
            options={
                'verbose_name': 'post category [en-us]',
                'verbose_name_plural': 'post categorys [en-us]',
                'db_table': 'newsapp_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
